theme = "onedark"
# blank defaults to $EDITOR
editor = ""
dir_editor = ""
auto_check_update = false
cd_on_quit = true
default_open_file_preview = true
show_image_preview = true
show_panel_footer_info = true
default_directory = "."
file_size_use_si = false
default_sort_type = 0
sort_order_reversed = false
case_sensitive_sort = false
shell_close_on_success = false
debug = false
ignore_missing_fields = false
# ================   Style =================
nerdfont = true
show_select_icons = true
transparent_background = true
file_preview_width = 0
code_previewer = "bat"
#
# The length of the sidebar. If you don't want to display the sidebar, you can input 0 directly. If you want to display the value, please place it in the range of 3-20.
sidebar_width = 20
border_top = "─"
border_bottom = "─"
border_left = "┃"
border_right = "┃"
border_top_left = "┏"
border_top_right = "┓"
border_bottom_left = "┗"
border_bottom_right = "┛"
border_middle_left = "┠"
border_middle_right = "┨"
# ==========PLUGINS========== #
metadata = true
# Enable MD5 checksum generation for files
enable_md5_checksum = false
# Zoxide support for the fast navigation
zoxide_support = true
